name: Deploy Backend to EC2

# mainブランチにpushされ、backendディレクトリに変更があった場合のみ実行
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # コードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v3

    # EC2にSSHしてデプロイ
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /opt/app/backend
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart flask-app

