name: Deploy to AWS CodeDeploy

# mainブランチにpushされたときに実行
on:
  push:
    branches:
      - main
  # 手動実行も可能にする
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3
      
      # AWS認証情報を設定
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      # CodeDeployでデプロイを作成
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          # デプロイメントを作成
          DEPLOYMENT_ID=$(aws deploy create-deployment \
            --application-name fest-quest-backend \
            --deployment-group-name production \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --query 'deploymentId' \
            --output text)
          
          echo "Deployment ID: $DEPLOYMENT_ID"
          echo "deployment_id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT
      
      # デプロイの完了を待つ
      - name: Wait for deployment to complete
        run: |
          echo "Waiting for deployment ${{ steps.deploy.outputs.deployment_id }} to complete..."
          
          # 最大10分間待つ
          for i in {1..60}; do
            STATUS=$(aws deploy get-deployment \
              --deployment-id ${{ steps.deploy.outputs.deployment_id }} \
              --query 'deploymentInfo.status' \
              --output text)
            
            echo "Deployment status: $STATUS"
            
            if [ "$STATUS" = "Succeeded" ]; then
              echo "Deployment succeeded!"
              exit 0
            elif [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Stopped" ]; then
              echo "Deployment failed with status: $STATUS"
              exit 1
            fi
            
            # 10秒待つ
            sleep 10
          done
          
          echo "Deployment timed out"
          exit 1