name: Deploy to Firebase Hosting on merge

on:
  push:
    branches: [ main ]   # live branch

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Flutter Web (release)
        run: flutter build web --release

      # Deploy to LIVE Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FESTQUEST_V2_8BC13 }}
          projectId: festquest-v2-8bc13
          channelId: live              # explicitly deploy live on merge
          # target: your_hosting_target # (optional if you use Hosting targets)
