name: Deploy to Firebase Hosting on PR

on: pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    # Prevents secrets from running on forked PRs
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        working-directory: quiz_rally
        run: flutter pub get

      - name: Build Flutter Web (release)
        working-directory: quiz_rally
        run: |
          touch .env
          echo BASE_URL=${{secrets.BASE_URL}} >> .env
          # Build Flutter web
          flutter build web --release
          # Copy .env to the assets folder after build
          cp .env build/web/assets/.env
          echo "Contents of build/web/assets after build:"
          ls -la build/web/assets/

      - name: Verify build output
        working-directory: quiz_rally
        run: |
          echo "=== Checking build output structure ==="
          ls -la build/web/
          echo ""
          echo "=== Checking assets directory ==="
          ls -la build/web/assets/
          echo ""
          echo "=== Checking if index.html exists ==="
          cat build/web/index.html | head -5
          echo ""
          echo "=== Ensuring .env is in assets ==="
          if [ ! -f build/web/assets/.env ]; then
            echo "Copying .env to build/web/assets/"
            cp .env build/web/assets/.env
          fi
          ls -la build/web/assets/.env

      # Deploy a PR preview to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FESTQUEST_V2_8BC13 }}
          projectId: festquest-v2-8bc13
          entryPoint: ./quiz_rally
          # target: your_hosting_target   # (optional if you use Hosting targets)
